apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:

      - type: container
        paths:
          - /var/log/containers/*.log

        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["http://elasticsearch.logging.svc.cluster.local:9200"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
  labels:
    app: filebeat

spec:
  selector:
    matchLabels:
      app: filebeat

  template:
    metadata:
      labels:
        app: filebeat

    spec:
      serviceAccountName: default

      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.5.1
        args: [ "-c", "/etc/filebeat.yml", "-e" ]

        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
          readOnly: true

        - name: containerlogs
          mountPath: /var/log/containers
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: filebeat-config

      - name: containerlogs
        hostPath:
          path: /var/log/containers
